name: Build and Push Docker Images

on:
  workflow_dispatch:
  ## if you want to do it automatically
  # push:
  #   branches: [ "main" ]

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Mirror WordPress image
      #   run: |
      #     docker pull wordpress:latest
      #     docker tag wordpress:latest ghcr.io/${{ github.repository_owner }}/wordpress:latest
      #     docker push ghcr.io/${{ github.repository_owner }}/wordpress:latest

      - name: Mirror WordPress image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/wordpress:latest
          build-args: IMAGE=wordpress:latest
          load: false


      ## if you want to use Dockerfile
      # - name: Build WordPress image
      #   run: |
      #     docker build -t ghcr.io/${{ github.repository_owner }}/wordpress:latest wordpress/

      # - name: Pull official WordPress image
      #   run: docker pull wordpress:latest

      # - name: Tag image for GHCR
      #   run: docker tag wordpress:latest ghcr.io/${{ github.repository_owner }}/wordpress:latest


      # - name: Push WordPress image
      #   run: |
      #     docker push ghcr.io/${{ github.repository_owner }}/wordpress:latest
